### ISSUE TITLE
getProofForLeafHash crashes when rate limit is reached

### ISSUE THREAD

**Issue by foolo** [WitnessCo/client#29]
When the rate limit hits, getProofForLeafHash in WitnessClient doesn't handle the error response from the server, and a SyntaxError is thrown to the application.

Steps to reproduce (happens when the rate limit is reached):

```
const witness = new WitnessClient(process.env.WITNESS_API_KEY);
const leafHash = witness.hash("...");
const proof = await witness.getProofForLeafHash(leafHash);
```

Result:

```
undefined:1
local_rate_limited
^

SyntaxError: Unexpected token 'l', "local_rate_limited" is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5329:19)
    at successSteps (node:internal/deps/undici/undici:5300:27)
    at fullyReadBody (node:internal/deps/undici/undici:1447:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:5309:7)
    at async w.getProofForLeafHash (/home/olof/checkout/zk/dkim-lookup/dkim-lookup-app/node_modules/.pnpm/@witnessco+client@0.1.14_viem@2.8.18/node_modules/@witnessco/client/dist/index.cjs:1:11722)
    at generateWitness (/home/olof/checkout/zk/dkim-lookup/dkim-lookup-app/src/lib/generateWitness.ts:19:16)

```

**Comment by sina-wit** [comment]
This should be fixed based on a previous version release; closing!
