### ISSUE TITLE
TypeError in WitnessClient constructor

### ISSUE THREAD

**Issue by foolo** [WitnessCo/client#33]
I just updated to Witness 0.4.1 and it seems there is now a new crash when instantiating WitnessClient.

Versions:
@witnessco/client: 0.4.1
viem: 2.10.8

Steps:
`new WitnessClient(process.env.WITNESS_API_KEY);`

Result:

```
TypeError: (0 , w.default) is not a function
    at A (/home/olof/checkout/zk/dkim-lookup/dkim-lookup-app/node_modules/.pnpm/@witnessco+client@0.4.1_viem@2.10.8/node_modules/@witnessco/client/dist/index.cjs:1:9126)
    at new k (/home/olof/checkout/zk/dkim-lookup/dkim-lookup-app/node_modules/.pnpm/@witnessco+client@0.4.1_viem@2.10.8/node_modules/@witnessco/client/dist/index.cjs:1:9649)
    at generateWitness (/home/olof/checkout/zk/dkim-lookup/dkim-lookup-app/src/lib/generateWitness.ts:8:18)
    at <anonymous> (/home/olof/checkout/zk/dkim-lookup/dkim-lookup-app/src/lib/utils_server.ts:70:3)
    at Array.forEach (<anonymous>)
    at addDomainSelectorPair (/home/olof/checkout/zk/dkim-lookup/dkim-lookup-app/src/lib/utils_server.ts:69:17)
    at process_line (/home/olof/checkout/zk/dkim-lookup/dkim-lookup-app/scripts/add_dsps.ts:13:15)
    at main (/home/olof/checkout/zk/dkim-lookup/dkim-lookup-app/scripts/add_dsps.ts:34:4)
```

**Comment by foolo** [comment]
here's a minimal example: [witness_repro_tmp1d-main.zip](https://github.com/WitnessCo/client/files/15347396/witness_repro_tmp1d-main.zip)
you can download it and run
```
npm install
npx tsx test_witness.ts
```

**Comment by sina-wit** [comment]
This should be fixed based on a previous version release; closing!
